<a href="https://colab.research.google.com/github/JennaSanks/ML_Libraries/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is Pandas?**

Definition:

Pandas is an open-source Python library used for loading, organizing, cleaning, analyzing, and manipulating structured data.

**It provides two main data structures:**

Series → A one-dimensional labeled array.
DataFrame → A two-dimensional table (like an Excel sheet or SQL table).

Think of Pandas as Excel + SQL + NumPy combined into Python.

**Import it with:**

**1. Import Pandas**

In [ ]:
import pandas as pd

**Why was Pandas created?**

NumPy is excellent at numerical computation, but it has limitations when working with real-world datasets.

Imagine student data.

Using NumPy:

In [ ]:
import numpy as np

students = np.array([
    ["Alice", 20, 85],
    ["Bob", 21, 90],
    ["Charlie", 19, 88]
])

print(students)

[['Alice' '20' '85']
 ['Bob' '21' '90']
 ['Charlie' '19' '88']]

**Problems:**

*  No column names.
*  Everything becomes strings because NumPy arrays typically have a single data type.
*  Hard to read.
*  Hard to filter by column name.

**Using Pandas:**

In [ ]:
import pandas as pd

students = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 88]
})

print(students)

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   19     88

Much cleaner.

**Why?**

pd is the standard alias used by the Python community.

**2. Create a Series**

A Series is a one-dimensional labeled array.

In [ ]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

**3. Create a DataFrame**

A DataFrame is a 2D table (rows and columns).

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 22, 21]
}

df = pd.DataFrame(data)

print(df)

      Name  Age
0    Alice   20
1      Bob   22
2  Charlie   21

**Why?**

Almost everything in Pandas revolves around DataFrames.

**4. Read Data**

In [ ]:
pd.read_csv()
pd.read_excel()
pd.read_json()
pd.read_sql()

In [ ]:
# Creating a file
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [20, 21, 22, 20, 23, 21],
    "Gender": ["Female", "Male", "Male", "Male", "Female", "Male"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune"],
    "Salary": [50000, 45000, 60000, 55000, 47000, 62000],
    "Marks": [85, 90, 78, 88, 91, 76]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students.csv", index=False)

# Read the CSV
df = pd.read_csv("students.csv")

print(df)

    ID     Name  Age  Gender Department    City  Salary  Marks
0  101    Alice   20  Female         IT  Mumbai   50000     85
1  102      Bob   21    Male         HR   Delhi   45000     90
2  103  Charlie   22    Male         IT    Pune   60000     78
3  104    David   20    Male    Finance  Mumbai   55000     88
4  105      Eva   23  Female         HR   Delhi   47000     91
5  106    Frank   21    Male         IT    Pune   62000     76

In [ ]:
# Example
df = pd.read_csv("students.csv")
print(df)

    ID     Name  Age  Gender Department    City  Salary  Marks
0  101    Alice   20  Female         IT  Mumbai   50000     85
1  102      Bob   21    Male         HR   Delhi   45000     90
2  103  Charlie   22    Male         IT    Pune   60000     78
3  104    David   20    Male    Finance  Mumbai   55000     88
4  105      Eva   23  Female         HR   Delhi   47000     91
5  106    Frank   21    Male         IT    Pune   62000     76

**Why?**

Load datasets into Pandas.

**5. Save Data**

In [ ]:
df.to_csv()
df.to_excel()
df.to_json()

In [ ]:
df.to_csv("output.csv", index=False)

**6. View Data**

In [ ]:
df.head()
df.tail()
df.sample()

In [ ]:
print(df.head())

    ID     Name  Age  Gender Department    City  Salary  Marks
0  101    Alice   20  Female         IT  Mumbai   50000     85
1  102      Bob   21    Male         HR   Delhi   45000     90
2  103  Charlie   22    Male         IT    Pune   60000     78
3  104    David   20    Male    Finance  Mumbai   55000     88
4  105      Eva   23  Female         HR   Delhi   47000     91

Shows the first 5 rows.

**7. Get Information**

In [ ]:
df.info()
df.describe()
df.shape
df.columns
df.index
df.dtypes

In [ ]:
# Example
print(df.shape)

(6, 8)

Meaning: 100 rows, 5 columns.

**8. Select Columns**

In [ ]:
df["Age"]

0    20
1    21
2    22
3    20
4    23
5    21
Name: Age, dtype: int64

or

In [ ]:
df[["Name", "Age"]]

      Name  Age
0    Alice   20
1      Bob   21
2  Charlie   22
3    David   20
4      Eva   23
5    Frank   21

**9. Select Rows**

loc (label-based)

In [ ]:
df.loc[0]

ID               101
Name           Alice
Age               20
Gender        Female
Department        IT
City          Mumbai
Salary         50000
Marks             85
Name: 0, dtype: object

iloc (position-based)

In [ ]:
df.iloc[0]

ID               101
Name           Alice
Age               20
Gender        Female
Department        IT
City          Mumbai
Salary         50000
Marks             85
Name: 0, dtype: object

Multiple rows

In [ ]:
df.iloc[0:5]

    ID     Name  Age  Gender Department    City  Salary  Marks
0  101    Alice   20  Female         IT  Mumbai   50000     85
1  102      Bob   21    Male         HR   Delhi   45000     90
2  103  Charlie   22    Male         IT    Pune   60000     78
3  104    David   20    Male    Finance  Mumbai   55000     88
4  105      Eva   23  Female         HR   Delhi   47000     91

**10. Filter Rows**

In [ ]:
df[df["Age"] > 20]

    ID     Name  Age  Gender Department   City  Salary  Marks
1  102      Bob   21    Male         HR  Delhi   45000     90
2  103  Charlie   22    Male         IT   Pune   60000     78
4  105      Eva   23  Female         HR  Delhi   47000     91
5  106    Frank   21    Male         IT   Pune   62000     76

In [ ]:
# Example
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 22, 18]
})

print(df[df["Age"] > 20])

  Name  Age
1  Bob   22

**11. Add a Column**

In [ ]:
df["Marks"] = [80, 90, 85]

**12. Delete Columns**

In [ ]:
df.drop("Marks", axis=1)

      Name  Age
0    Alice   20
1      Bob   22
2  Charlie   18

In [ ]:
# Multiple columns
df.drop(["Age", "Marks"], axis=1)

      Name
0    Alice
1      Bob
2  Charlie

**13. Rename Columns**

In [ ]:
df.rename(columns={"Age": "Student Age"})

      Name  Student Age  Marks
0    Alice           20     80
1      Bob           22     90
2  Charlie           18     85

**14. Missing Values**

In [ ]:
df.isnull()
df.notnull()
df.dropna()
df.fillna()

In [ ]:
# Example
df.fillna(0)

      Name  Age  Marks
0    Alice   20     80
1      Bob   22     90
2  Charlie   18     85

Replace missing values with 0.

**15. Sorting**

In [ ]:
df.sort_values("Age")

      Name  Age  Marks
2  Charlie   18     85
0    Alice   20     80
1      Bob   22     90

In [ ]:
# Descending
df.sort_values("Age", ascending=False)

      Name  Age  Marks
1      Bob   22     90
0    Alice   20     80
2  Charlie   18     85

**16. Grouping**

In [ ]:
# Creating DataFreme
import pandas as pd

# Creating DataFrame
data = {
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 45000, 60000, 55000, 47000, 62000],
    "Age": [20, 21, 22, 23, 21, 24],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)

print(df)

    ID     Name Department  Salary  Age    City
0  101    Alice         IT   50000   20  Mumbai
1  102      Bob         HR   45000   21   Delhi
2  103  Charlie         IT   60000   22    Pune
3  104    David    Finance   55000   23  Mumbai
4  105      Eva         HR   47000   21   Delhi
5  106    Frank         IT   62000   24    Pune

In [ ]:
df.groupby("Department")

In [ ]:
# Example
df.groupby("Department")["Salary"].mean()

Department
Finance    55000.000000
HR         46000.000000
IT         57333.333333
Name: Salary, dtype: float64

Very common in data analysis.

**17. Aggregation**

In [ ]:
df.mean()
df.sum()
df.min()
df.max()
df.count()
df.std()

**18. Unique Values**

In [ ]:
# Daraset Creation
import pandas as pd

# Dataset Creation
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Age": [20, 21, 22, 23, 21, 24, 22, 23],
    "Gender": ["Female", "Male", "Male", "Male", "Female", "Male", "Female", "Male"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Marketing", "Finance"],
    "Salary": [50000, 45000, 60000, 55000, 47000, 62000, 52000, 58000],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi", "Pune", "Bangalore", "Mumbai"],
    "Experience": [1, 2, 3, 2, 1, 4, 2, 3],
    "Performance": ["A", "B", "A", "B", "A", "A", "C", "B"],
    "Joining_Year": [2023, 2022, 2021, 2022, 2023, 2020, 2022, 2021]
}

df = pd.DataFrame(data)

print(df)

    ID     Name  Age  Gender Department  Salary       City  Experience  \
0  101    Alice   20  Female         IT   50000     Mumbai           1
1  102      Bob   21    Male         HR   45000      Delhi           2
2  103  Charlie   22    Male         IT   60000     Mumbai           3
3  104    David   23    Male    Finance   55000       Pune           2
4  105      Eva   21  Female         HR   47000      Delhi           1
5  106    Frank   24    Male         IT   62000       Pune           4
6  107    Grace   22  Female  Marketing   52000  Bangalore           2
7  108    Henry   23    Male    Finance   58000     Mumbai           3

  Performance  Joining_Year
0           A          2023
1           B          2022
2           A          2021
3           B          2022
4           A          2023
5           A          2020
6           C          2022
7           B          2021

In [ ]:
df["City"].unique()

array(['Mumbai', 'Delhi', 'Pune', 'Bangalore'], dtype=object)

In [ ]:
# Count them
df["City"].nunique()

4

In [ ]:
# Frequency
df["City"].value_counts()

City
Mumbai       3
Delhi        2
Pune         2
Bangalore    1
Name: count, dtype: int64

**19. Duplicate Data**

In [ ]:
df.duplicated()
df.drop_duplicates()

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance,Joining_Year
0,101,Alice,20,Female,IT,50000,Mumbai,1,A,2023
1,102,Bob,21,Male,HR,45000,Delhi,2,B,2022
2,103,Charlie,22,Male,IT,60000,Mumbai,3,A,2021
3,104,David,23,Male,Finance,55000,Pune,2,B,2022
4,105,Eva,21,Female,HR,47000,Delhi,1,A,2023
5,106,Frank,24,Male,IT,62000,Pune,4,A,2020
6,107,Grace,22,Female,Marketing,52000,Bangalore,2,C,2022
7,108,Henry,23,Male,Finance,58000,Mumbai,3,B,2021

**20. Merge Data**

In [ ]:
# Creating DataFrame
import pandas as pd

# First DataFrame
df1 = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"]
})

# Second DataFrame
df2 = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Salary": [50000, 45000, 60000, 55000, 47000],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi"]
})

In [ ]:
pd.merge(df1, df2, on="ID")

    ID     Name Department  Salary    City
0  101    Alice         IT   50000  Mumbai
1  102      Bob         HR   45000   Delhi
2  103  Charlie         IT   60000  Mumbai
3  104    David    Finance   55000    Pune
4  105      Eva         HR   47000   Delhi

SQL-like joins.

**21. Concatenate**

In [ ]:
pd.concat([df1, df2])

    ID     Name Department   Salary    City
0  101    Alice         IT      NaN     NaN
1  102      Bob         HR      NaN     NaN
2  103  Charlie         IT      NaN     NaN
3  104    David    Finance      NaN     NaN
4  105      Eva         HR      NaN     NaN
0  101      NaN        NaN  50000.0  Mumbai
1  102      NaN        NaN  45000.0   Delhi
2  103      NaN        NaN  60000.0  Mumbai
3  104      NaN        NaN  55000.0    Pune
4  105      NaN        NaN  47000.0   Delhi

**22. Apply Functions**

In [ ]:
df["Age"].apply(lambda x: x + 5)

0    25
1    26
2    27
3    28
4    26
5    29
6    27
7    28
Name: Age, dtype: int64

Very useful for transformations.

**23. String Operations**

In [ ]:
df["Name"].str.upper()
df["Name"].str.lower()
df["Name"].str.contains("A")

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Name, dtype: bool

**24. Datetime**

In [ ]:
pd.to_datetime()

TypeError: to_datetime() missing 1 required positional argument: 'arg'

In [ ]:
# Creation of data
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 47000],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi"],
    "Date": [
        "2023-01-15",
        "2022-05-20",
        "2021-08-10",
        "2022-11-30",
        "2023-03-05"
    ]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

print(df)
print(df.dtypes)

      Name Department  Salary    City       Date
0    Alice         IT   50000  Mumbai 2023-01-15
1      Bob         HR   45000   Delhi 2022-05-20
2  Charlie         IT   60000  Mumbai 2021-08-10
3    David    Finance   55000    Pune 2022-11-30
4      Eva         HR   47000   Delhi 2023-03-05
Name                  object
Department            object
Salary                 int64
City                  object
Date          datetime64[ns]
dtype: object

In [ ]:
# Example
df["Date"] = pd.to_datetime(df["Date"])

**25. Index Operations**

In [ ]:
df.set_index()
df.reset_index()

In [ ]:
# Set Name as index
df = df.set_index("Name")

# Reset the index
df = df.reset_index()

print(df)

      Name Department  Salary    City       Date
0    Alice         IT   50000  Mumbai 2023-01-15
1      Bob         HR   45000   Delhi 2022-05-20
2  Charlie         IT   60000  Mumbai 2021-08-10
3    David    Finance   55000    Pune 2022-11-30
4      Eva         HR   47000   Delhi 2023-03-05

**26. Correlation**

In [ ]:
df.corr()

In [ ]:
import pandas as pd

data = {
    "Age": [20, 22, 24, 26, 28],
    "Salary": [30000, 40000, 50000, 60000, 70000],
    "Experience": [1, 2, 3, 4, 5]
}

df = pd.DataFrame(data)

print(df.corr())

            Age  Salary  Experience
Age         1.0     1.0         1.0
Salary      1.0     1.0         1.0
Experience  1.0     1.0         1.0

Useful for feature analysis.

**27. Pivot Table**

In [ ]:
pd.pivot_table()

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 47000]
}

df = pd.DataFrame(data)

pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)

print(pivot)

             Salary
Department
Finance     55000.0
HR          46000.0
IT          55000.0

**28. Boolean Filtering**

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 22, 23, 24],
    "Marks": [85, 75, 90, 80, 95]
}

df = pd.DataFrame(data)

result = df[(df["Age"] > 20) & (df["Marks"] > 80)]

print(result)

      Name  Age  Marks
2  Charlie   22     90
4      Eva   24     95

Using OR

In [ ]:
df[(df["Age"] > 20) | (df["Marks"] > 80)]

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     75
2  Charlie   22     90
3    David   23     80
4      Eva   24     95

**29. Iterating (Use Sparingly)**

In [ ]:
for index, row in df.iterrows():
    print(row["Name"])

Alice
Bob
Charlie
David
Eva

Note: Prefer vectorized operations instead of loops whenever possible.

**30. Useful Attributes**

In [ ]:
df.shape
df.size
df.columns
df.index
df.values
df.dtypes
df.empty

**Essential Additional Pandas Topics**

**1. query()**

Filter data using SQL-like syntax.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 25, 18]
})

print(df.query("Age > 20"))

  Name  Age
1  Bob   25

**2. assign()**

Create new columns without modifying the original DataFrame.

In [ ]:
df = df.assign(Adult=df["Age"] >= 18)

print(df)

      Name  Age  Adult
0    Alice   20   True
1      Bob   25   True
2  Charlie   18   True

**3. map()**

Replace values in a Series.

In [ ]:
import pandas as pd

grades = pd.Series(["A", "B", "A", "C"])

print(grades.map({"A": 4, "B": 3, "C": 2}))

0    4
1    3
2    4
3    2
dtype: int64

**4. replace()**

Replace values.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Gender": ["M", "F", "M"]
})

print(df.replace({"M": "Male", "F": "Female"}))

   Gender
0    Male
1  Female
2    Male

**5. astype()**

Change data types.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Age": ["20", "21", "22"]
})

df["Age"] = df["Age"].astype(int)

print(df.dtypes)

Age    int64
dtype: object

**6. sort_index()**

In [ ]:
df.sort_index()

   Age
0   20
1   21
2   22

Sort by index instead of values.

**7. nlargest() and nsmallest()**

In [ ]:
df.nlargest(3, "Marks")

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 22, 23, 24],
    "Marks": [85, 75, 90, 80, 95]
}

df = pd.DataFrame(data)

print(df.nlargest(3, "Marks"))

      Name  Age  Marks
4      Eva   24     95
2  Charlie   22     90
0    Alice   20     85

In [ ]:
df.nsmallest(3, "Marks")

    Name  Age  Marks
1    Bob   21     75
3  David   23     80
0  Alice   20     85

Very useful for finding top performers.

**8. isin()**

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 47000],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)

Checks membership in a list.

**9. between()**

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 22, 23, 26],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 47000],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)

df[df["Age"].between(18, 25)]

      Name  Age Department  Salary    City
0    Alice   20         IT   50000  Mumbai
1      Bob   21         HR   45000   Delhi
2  Charlie   22         IT   60000  Mumbai
3    David   23    Finance   55000    Pune

In [ ]:
# Much cleaner than:
(df["Age"] >= 18) & (df["Age"] <= 25)

0     True
1     True
2     True
3     True
4    False
Name: Age, dtype: bool

**10. sample()**

Random rows.

In [ ]:
df.sample(5)

      Name  Age Department  Salary    City
1      Bob   21         HR   45000   Delhi
2  Charlie   22         IT   60000  Mumbai
4      Eva   26         HR   47000   Delhi
0    Alice   20         IT   50000  Mumbai
3    David   23    Finance   55000    Pune

Random 5 rows.

**11. describe(include='all')**

Works for text columns too.

In [ ]:
df.describe(include="all")

         Name        Age Department        Salary    City
count       5   5.000000          5      5.000000       5
unique      5        NaN          3           NaN       3
top     Alice        NaN         IT           NaN  Mumbai
freq        1        NaN          2           NaN       2
mean      NaN  22.400000        NaN  51400.000000     NaN
std       NaN   2.302173        NaN   6107.372594     NaN
min       NaN  20.000000        NaN  45000.000000     NaN
25%       NaN  21.000000        NaN  47000.000000     NaN
50%       NaN  22.000000        NaN  50000.000000     NaN
75%       NaN  23.000000        NaN  55000.000000     NaN
max       NaN  26.000000        NaN  60000.000000     NaN

**12. memory_usage()**

Shows memory consumption.

In [ ]:
df.memory_usage()

Index         132
Name           40
Age            40
Department     40
Salary         40
City           40
dtype: int64

Useful for large datasets.

**13. pipe()**

Chain operations.

In [ ]:
df.pipe(function_name)

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Salary": [50000, 45000, 60000]
}

df = pd.DataFrame(data)

# Create a function
def increase_salary(df):
    df["Salary"] = df["Salary"] * 1.10
    return df

# Pass DataFrame to the function
df = df.pipe(increase_salary)

print(df)

      Name   Salary
0    Alice  55000.0
1      Bob  49500.0
2  Charlie  66000.0

Mostly used in advanced projects.

**14. MultiIndex**

Hierarchical indexing.

**Example:**

Country
    
    City

Useful in grouped reports.

**15. Categorical Data**

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 22, 23, 24],
    "Marks": [85, 90, 78, 88, 91],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)

# Convert City to category
df["City"] = df["City"].astype("category")

print(df.dtypes)

Name       object
Age         int64
Marks       int64
City     category
dtype: object

Benefits:

*   Less memory
*   Faster operations
*   Better for repeated text values

**16. Window Functions**

Rolling averages.

In [ ]:
import pandas as pd

data = {
    "Day": [1, 2, 3, 4, 5, 6],
    "Sales": [100, 150, 200, 250, 300, 350]
}

df = pd.DataFrame(data)

df["Rolling_Mean"] = df["Sales"].rolling(3).mean()

print(df)

   Day  Sales  Rolling_Mean
0    1    100           NaN
1    2    150           NaN
2    3    200         150.0
3    4    250         200.0
4    5    300         250.0
5    6    350         300.0

Used in finance and time-series.

**17. shift()**

In [ ]:
df["Previous"] = df["Sales"].shift(1)

Gets previous row values.

**18. diff()**

In [ ]:
df["Difference"] = df["Sales"].diff()

Difference between consecutive rows.

**19. rank()**

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [90, 75, 85]
})

df["Rank"] = df["Marks"].rank(ascending=False)

print(df)

  Name  Marks  Rank
0    A     90   1.0
1    B     75   3.0
2    C     85   2.0

Assigns ranks to values.

**20. explode()**

Converts list values into separate rows.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice"],
    "Skills": [["Python", "SQL"]]
})

print(df.explode("Skills"))

    Name  Skills
0  Alice  Python
0  Alice     SQL